from pathlib import Path
import numpy as np,math,json
D=Path(__file__).resolve().parent;R=D.parent;OLD=R/'weather-hybrid-rain-hero-20261008-0515';src=np.maximum(np.load(OLD/'plate-scene-linear.npy'),0);sh,sw=src.shape[:2];field=np.load(R/'weather-lateral-shared-field-20261008-0919/lateral-neutral-shared-field.npy').astype(np.float64);H,W=field.shape[:2];uu,vv=np.meshgrid((np.arange(W)+.5)/W,(np.arange(H)+.5)/H);phi=(uu-.5)*2*np.pi;el=(vv-.5)*np.pi;dirs=np.stack([np.cos(el)*np.sin(phi),np.cos(el)*np.cos(phi),np.sin(el)],-1);dw=np.cos(el)*(2*np.pi/W)*(np.pi/H);Y=np.array([.2126,.7152,.0722]);key=np.array([-.22311237454414368,.9686135649681091,.10958324372768402]);key/=np.linalg.norm(key);kp=np.arctan2(key[0],key[1]);ke=np.arcsin(key[2]);u0=.1620501921902606;v0=.668960401383117;U=(u0+(phi-kp)/(2*np.pi))%1;E=np.maximum(el,0);sy=np.where(E<=ke,.59-(.59-(1-v0))*E/ke,(1-v0)*(1-(E-ke)/(np.pi/2-ke)));sy=np.clip(sy,0,.59)
def sample(U,V):
 fx=U*(sw-1);fy=V*(sh-1);ix=np.floor(fx).astype(int);iy=np.floor(fy).astype(int);dx=fx-ix;dy=fy-iy;ix1=np.minimum(ix+1,sw-1);iy1=np.minimum(iy+1,sh-1);return src[iy,ix]*(1-dx)[...,None]*(1-dy)[...,None]+src[iy,ix1]*dx[...,None]*(1-dy)[...,None]+src[iy1,ix]*(1-dx)[...,None]*dy[...,None]+src[iy1,ix1]*dx[...,None]*dy[...,None]
cloud=sample(U,sy);lum=cloud@Y

def lobe(direction,sigma):
 d=np.array(direction,float);d/=np.linalg.norm(d);fp=np.arctan2(d[0],d[1]);fe=np.arcsin(d[2]);fU=(u0+(fp-kp)/(2*np.pi))%1;fV=(1-v0)*(1-(fe-ke)/(np.pi/2-ke));cl=float(sample(np.array(fU),np.array(fV))@Y);structure=np.clip(lum/max(cl,1e-5),.35,1.6);shape=np.exp((dirs@d-1)/math.radians(sigma)**2);return shape[...,None]*np.array([18,15.3,11.7])*structure[...,None],d
cfg=json.loads((R/'weather-lateral-shared-field-20261008-0919/SHARED-FIELD-CONTRACT.json').read_text());old,od=lobe([-.94,.10,.32],12);old*=cfg['coefficients']['warm'];new,nd=lobe([-.89,.08,.45],6.5);old_energy=float(((old@Y)*dw).sum());new_energy=float(((new@Y)*dw).sum());new*=old_energy/new_energy;fraction=.75;out=np.maximum(field+fraction*(new-old),0).astype(np.float32);assert np.isfinite(out).all();np.save(D/'coordinated-shared-opening.npy',out)
# Actual current camera and translated Ball, preserving the analytic diffuse budget.
M=np.array(json.loads((R/'weather-canonical-sphere-rain-20261009-0119/SOURCE-INSPECTION.json').read_text())['camera_matrix']);O=M[:3,3];pose=json.loads((R/'weather-right-umbrella-correction-20261009-0153/RIGHT-POSE-GEOMETRY-CHECK.json').read_text());C=np.array([3.265336751937866,0,.8799997568130493])+np.array(pose['Ball_root_translation_AU']);normals=[];pixels=[]
for py in range(251,393,10):
 for px in range(484,628,10):
  ray=M[:3,:3]@np.array([(px-450)/1325,(300-py)/1325,-1]);ray/=np.linalg.norm(ray);oc=O-C;b=oc@ray;disc=b*b-(oc@oc-.88**2)
  if disc<0:continue
  t=-b-np.sqrt(disc);normals.append((O+ray*t-C)/.88);pixels.append([px,py])
fdirs=dirs.reshape(-1,3);area=dw.ravel();oldY=(field@Y).ravel();newY=(out@Y).ravel();oldirr=[];newirr=[]
for start in range(0,len(normals),8):
 n=np.array(normals[start:start+8]);weight=np.maximum(fdirs@n.T,0)*area[:,None]/np.pi;oldirr.extend(oldY@weight);newirr.extend(newY@weight)
oldirr=np.array(oldirr);newirr=np.array(newirr);ratio=newirr/oldirr;delta=newirr-oldirr
report={'status':'One authored shared-light revision, no render yet','source_field':'lateral-neutral-shared-field.npy','new_field':'coordinated-shared-opening.npy','all_objects_all_ray_types_share_field':True,'backdrop_image_and_visible_warm_source_component_unchanged':True,'old_lateral_warm_direction':od.tolist(),'new_lateral_core_direction':nd.tolist(),'old_sigma_deg':12,'new_core_sigma_deg':6.5,'warm_energy_fraction_redistributed':fraction,'old_halo_fraction':1-fraction,'warm_integrated_luminance_energy_preserved':True,'mean_spherical_Y_before':float(((field@Y)*dw).sum()/(4*np.pi)),'mean_spherical_Y_after':float(((out@Y)*dw).sum()/(4*np.pi)),'warm_peak_RGB_before':old.reshape(-1,3).max(0).tolist(),'warm_peak_RGB_core':new.reshape(-1,3).max(0).tolist(),'actual_Ball_analytic_visible_normals':len(normals),'Ball_unoccluded_diffuse_Y_ratio_percentiles':np.percentile(ratio,[0,5,50,95,100]).tolist(),'Ball_diffuse_delta_Y_percentiles':np.percentile(delta,[0,50,100]).tolist(),'assumptions':['Analytic Ball sphere normals and unoccluded diffuse irradiance only; full Cycles specular, occlusion and multi-interface response remain unverified until crop','Core remains lateral-left and warm, raised about8degrees; no object/ray-specific brightening or added emission','Integrated warm energy preserved; this is angular radiance redistribution, not recovered measured HDR or global exposure increase'],'probes':[{'pixel':p,'old_Y':float(a),'new_Y':float(b),'ratio':float(c)}for p,a,b,c in zip(pixels,oldirr,newirr,ratio)]};(D/'SHARED-OPENING-CHANGE.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:v for k,v in report.items()if k!='probes'},indent=2))
