import {withoutMotionClockFix} from './motion-clock-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {fixture} from './fixtures/continuity-fixture.mjs';
import {SEND_PATH} from '../../runtime/chat/send-path.js';
const root=fileURLToPath(new URL('../../runtime/',import.meta.url)),base=new URL('./fixtures/accepted-baseline/',import.meta.url),host=fs.readFileSync(path.join(root,'chat-host.js'),'utf8');
const make=label=>fixture({flowPath:path.join(root,'chat/chat-reading-flow.js'),projectionPath:path.join(root,'chat/send-continuity.js'),hostSource:host,label});
test('preserved chat, motion, and eye primitives match accepted baseline; only approved D default and elapsed-time wrapper differ',()=>{
 const files=[...fs.readdirSync(path.join(root,'chat')).filter(p=>p.startsWith('send-')).map(p=>'chat/'+p),'chat/chat-reading-flow.js','chat/chat-reading-interior.js','chat/chat-reading.css','chat/chat-turn-scroll.js','chat/contextual-chat-layout.js','chat-motion.js','chat-contour.js','world/vendor/aora/rings.js'];
 for(const p of files){let actual=fs.readFileSync(path.join(root,p),'utf8');if(p==='chat-motion.js')actual=withoutMotionClockFix(actual);if(p==='chat/send-continuity.js')actual=actual.replace("includes(requestedVariant)?requestedVariant:'D'","includes(requestedVariant)?requestedVariant:'A'");assert.equal(actual,fs.readFileSync(new URL(p,base),'utf8'),p);}assert.equal(SEND_PATH.duration,.32);
});
test('normal candidate URL defaults to accepted D320 without query overrides',async()=>{const f=await make('candidate-default-D320');try{assert.equal(f.doc.defaultView.location.search,'');assert(f.send('默认发送路径'));assert.equal(f.projection.state().variant,'D');assert.equal(f.gsap.tweens.at(-1).duration,.32);f.advance(.321);assert.equal(f.projection.state().active,false);}finally{f.destroy();}});
test('actual accepted D320 sends first/later messages without losing the next draft or wrapper identity',async()=>{const f=await make('mobile-flow-D320');f.doc.defaultView.location.search='?sendVariant=D';const input=f.ui.input,field=f.ui.field;try{for(let i=0;i<3;i++){assert(f.send('先把问题说清楚，\n再找到一个验证。\n一步一步来。'));assert.equal(f.gsap.tweens.at(-1).duration,.32);assert.equal(f.projection.state().kind,'launch');f.advance(.08);f.ui.input.value='下一条未发送草稿';f.advance(.241);assert.equal(f.ui.input.value,'下一条未发送草稿');assert.equal(f.projection.state().active,false);assert.equal(f.ui.input,input);assert.equal(f.ui.field,field);assert.equal(f.doc.body.querySelectorAll('.send-continuity-flight').length,0);f.flushResponse();}}finally{f.destroy();}});
test('accepted D consumes viewport BCR with nonzero origin and null contour without another origin adapter',async()=>{const f=await make('mobile-flow-global-basis'),dx=23,dy=347;try{for(const n of [f.ui.input,f.ui.field,f.core.ctx.layout.plane,f.core.ctx.layout.scroll]){n.nativeRect.x+=dx;n.nativeRect.y+=dy;}f.doc.messageRight+=dx;const create=f.doc.createElement;f.doc.createElement=function(tag){const n=create(tag),get=n.getBoundingClientRect.bind(n);n.getBoundingClientRect=()=>{const r=get();return n.matches('.message.user')?{...r,y:r.y+dy,top:r.top+dy,bottom:r.bottom+dy}:r;};return n;};f.core.canvas.target={x:123,y:427,w:420,h:600};f.core.canvas.presented={...f.core.canvas.target};f.core.ctx.contourPose=null;f.ui.panel.dataset.sendVariant='D';assert(f.send('原生文档坐标'));const tween=f.gsap.tweens.at(-1);tween.proxy.p=1;tween.config.onUpdate();const p=f.projection.state().frame,r=f.users[0].getBoundingClientRect();assert.equal(p.x,r.x);assert.equal(p.y,r.y);assert.equal(p.textY,r.y+10);assert.equal(f.doc.body.querySelector('.send-continuity-flight').style.clipPath,'inset(427px 457px 0px 123px round 24px)');}finally{f.destroy();}});
test('real Send composition guard keeps native draft intact, then accepts committed text',async()=>{const f=await make('mobile-flow-ime');try{f.ui.input.value='正在选择候选词';for(const fn of f.ui.input.listeners.get('compositionstart'))fn();assert.equal(f.flow.send(),false);assert.equal(f.ui.input.value,'正在选择候选词');assert.equal(f.users.length,0);for(const fn of f.ui.input.listeners.get('compositionend'))fn();assert(f.flow.send());assert.equal(f.users[0].textContent,'正在选择候选词');f.close();f.hide();assert.equal(f.doc.body.querySelectorAll('.send-continuity-flight').length,0);}finally{f.destroy();}});
test('flow source publishes actual panel viewport BCR and clears motion contour before enabling input',()=>{assert.match(host,/flowPage.active\?rectangle\(panel\):flowPage.measure\(\)/);assert.match(host,/core.canvas.target=\{\.\.\.r\}/);assert.match(host,/if\(flowPage.active\)\{core.canvas.presented=\{\.\.\.r\};core.ctx.contourPose=null;/);const paint=host.slice(host.indexOf(' function paint('),host.indexOf(' function step('));assert.match(host,/function flowHandoffReady\(m\)\{const r=core.canvas.target;return m.phase==='open'/);assert.ok(paint.indexOf('flowPage.stage')<paint.indexOf('flowPage.commit'));assert.ok(paint.indexOf('flowPage.commit')<paint.indexOf("commitMobileLayout('handoff'"));assert.ok(paint.indexOf("commitMobileLayout('handoff'")<paint.indexOf('panel.inert=false;ui.input.disabled=false'));assert.match(paint,/const interactive=m.interactive&&!flowPage.owned/);assert.doesNotMatch(paint,/ui.input.focus\(/);});
