import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createChatTurnScroll} from '../../runtime/chat/chat-turn-scroll.js';
class Target{constructor(){this.listeners=new Map()}addEventListener(k,fn){const s=this.listeners.get(k)||new Set();s.add(fn);this.listeners.set(k,s)}removeEventListener(k,fn){this.listeners.get(k)?.delete(fn)}dispatchEvent(e){for(const fn of [...(this.listeners.get(e.type)||[])])fn(e)}}
function setup(){const win=new Target(),doc=new Target(),host=new Target(),values=new Map();host.style={getPropertyValue:k=>values.get(k)||'',getPropertyPriority:()=>'',setProperty:(k,v)=>values.set(k,v),removeProperty:k=>values.delete(k)};const messages={ownerDocument:doc};host.contains=n=>n===messages;doc.defaultView=win;doc.body={};return{win,doc,host,messages};}
const source=fs.readFileSync(new URL('../../runtime/chat-host.js',import.meta.url),'utf8'),handler=source.match(/window\.addEventListener\('pageshow',event=>\{.*?\}\);/)[0];
test('persisted native-flow page resumes the actual retained transcript owner without remount',()=>{const {win,host,messages}=setup(),scroll=createChatTurnScroll({messages,getHost:()=>host,hosts:[host],gsap:{ticker:{add(){},remove(){}},to(){throw Error('No turn')}},initiallyOpen:true,window:win});let commits=0,poll=0;new Function('window','open','flowPage','core','flow','viewportCommit','keyboardObserver',handler)(win,true,{owned:true,active:true},{chatWanted:true},{setOpen:v=>scroll.setOpen(v)},()=>commits++,{start:()=>poll++});win.dispatchEvent({type:'pagehide',persisted:true});assert.equal(scroll.state().open,false);win.dispatchEvent({type:'pageshow',persisted:true});assert.equal(scroll.state().open,true);assert.equal(commits,1);assert.equal(poll,0);scroll.destroy();});
test('closed/unwanted/fresh navigation cannot resume flow; desktop keeps its old observer path',()=>{for(const [open,wanted,active,persisted] of [[false,true,true,true],[true,false,true,true],[true,true,true,false],[true,true,false,true]]){const win=new Target();let resumes=0,commits=0,poll=0;new Function('window','open','flowPage','core','flow','viewportCommit','keyboardObserver',handler)(win,open,{owned:active,active},{chatWanted:wanted},{setOpen:()=>resumes++},()=>commits++,{start:()=>poll++});win.dispatchEvent({type:'pageshow',persisted});assert.equal(resumes,0);assert.equal(commits,0);assert.equal(poll,open&&persisted&&!active?1:0);}});

test('persisted opening/handoff resumes the same wanted mobile transcript before native input becomes active',()=>{for(const phase of ['opening','handoff']){const {win,host,messages}=setup(),scroll=createChatTurnScroll({messages,getHost:()=>host,hosts:[host],gsap:{ticker:{add(){},remove(){}},to(){throw Error('No turn')}},initiallyOpen:true,window:win});let commits=0,poll=0;new Function('window','open','flowPage','core','flow','viewportCommit','keyboardObserver',handler)(win,true,{owned:true,active:false,phase},{chatWanted:true},{setOpen:v=>scroll.setOpen(v)},()=>commits++,{start:()=>poll++});win.dispatchEvent({type:'pagehide',persisted:true});assert.equal(scroll.state().open,false);win.dispatchEvent({type:'pageshow',persisted:true});assert.equal(scroll.state().open,true);assert.equal(commits,1);assert.equal(poll,0);scroll.destroy();}});
