import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createMobileFlowPage,mobileFlowEligible,mobileFlowPreview} from '../../runtime/chat/chat-mobile-flow-page.js';
import {createChatPageLock} from '../../runtime/chat/chat-page-lock.js';
import {flowFixture} from './flow-fixture.mjs';
function enter(f){const page=createMobileFlowPage(f.doc),lock=createChatPageLock(f.doc),r=page.prepare(f.panel,f.html.scrollTop);lock.lock();const handoff=page.stage(()=>lock.unlock({restoreScroll:false}));page.commit();return{page,lock,r,handoff};}
test('normal-flow preview is explicit, does not spoof viewport/device, and desktop auto eligibility is unchanged',()=>{const f=flowFixture();f.win.innerWidth=1180;f.win.matchMedia=()=>({matches:false});assert.equal(mobileFlowEligible(f.win),false);f.win.location.search='?chatPagePreview=1';assert.equal(mobileFlowEligible(f.win),true);assert.equal(mobileFlowPreview(f.win),true);assert.equal(f.win.innerWidth,1180);f.win.location.search='?chatPagePreview=0';assert.equal(mobileFlowEligible(f.win),false);f.win.innerWidth=402;assert.equal(mobileFlowEligible(f.win),true);});
test('handoff releases fixed body without restoring deep scroll, retains the same input and one sibling canvas',()=>{const f=flowFixture(),parent=f.world.parentNode,originalInput=f.input,{page,lock,r,handoff}=enter(f);assert.deepEqual(handoff.before,handoff.after);assert.deepEqual(handoff.after,r);assert.equal(lock.locked,false);assert.equal(f.body.style.position,'');assert.equal(page.active,true);assert.equal(f.panel.parentNode,page.frame);assert.equal(f.input,originalInput);assert.equal(f.input.parentNode,f.panel);assert.equal(f.input.value,'保留这段草稿\n以及下一行');assert.equal(f.input.selectionStart,2);assert.equal(f.input.selectionEnd,6);assert.equal(f.world.parentNode,parent);assert.equal(f.world.children[0],f.canvas);assert.equal(f.log.filter(e=>e.type==='scroll').length,0);assert.equal(page.offset(),2461);assert.equal(f.html.scrollTop,0);});
test('only explicit site roots leave flow; active detail node/reader and world identities survive',()=>{const f=flowFixture(),detail=f.reader,{page}=enter(f);for(const node of f.site)assert.equal(node.style.display,'none');assert.equal(f.world.style.display,'');assert.equal(f.canvas.parentNode,f.world);assert.equal(f.reader,detail);assert.equal(f.reader.parentNode,f.stage);assert.equal(page.owned,true);assert.equal(f.doc.body.dataset.mobileChatPage,'true');});
test('close restores site layout then detail reading offset then page scroll once, restores exact inert/history/display state',()=>{const f=flowFixture(),display=f.app.style.snapshot(),inert=f.stage.inert,{page}=enter(f);f.reader.scrollTop=0;page.beginExit();assert.equal(f.panel.parentNode,f.body);assert.equal(f.panel.style.width,'386px');assert.equal(f.panel.style.height,'650px');page.restoreSite();page.restoreSite();page.finish();page.finish();const scroll=f.log.filter(e=>e.type==='scroll');assert.equal(scroll.length,1);assert.equal(scroll[0].top,2461);assert.equal(scroll[0].left,5);assert.equal(scroll[0].readerTop,713);assert.equal(scroll[0].appDisplay,'block');assert.deepEqual(f.app.style.snapshot(),display);assert.equal(f.reader.scrollTop,713);assert.equal(f.stage.inert,inert);assert.equal(f.win.history.scrollRestoration,'auto');assert.equal(page.owned,false);assert.equal(f.log.findIndex(e=>e.type==='personalos:mobile-chat-restoring')<f.log.findIndex(e=>e.type==='scroll'),true);assert.equal(f.log.at(-1).type,'personalos:mobile-chat-release');});
test('close before handoff never removes site and leaves the original lock to restore once',()=>{const f=flowFixture(),page=createMobileFlowPage(f.doc),lock=createChatPageLock(f.doc);page.prepare(f.panel,2461);lock.lock();page.finish();assert.equal(f.app.style.display,'block');assert.equal(f.panel.parentNode,f.body);assert.equal(f.log.filter(e=>e.type==='scroll').length,0);lock.unlock();lock.unlock();assert.equal(f.log.filter(e=>e.type==='scroll').length,1);assert.equal(f.html.scrollTop,2461);});
test('close interrupted before site release reuses the original snapshot without a stale restoration',()=>{const f=flowFixture(),{page}=enter(f);page.beginExit();page.prepare(f.panel,0);assert.equal(page.offset(),2461);page.stage(()=>{});page.commit();assert.equal(f.log.filter(e=>e.type==='scroll').length,0);assert.equal(page.active,true);assert.equal(f.app.style.display,'none');page.beginExit();page.restoreSite();page.finish();assert.equal(f.log.filter(e=>e.type==='scroll').length,1);assert.equal(f.html.scrollTop,2461);});
test('reopen after returning-phase release keeps original saved offset and preserves snapshot/inert through the second handoff',()=>{const f=flowFixture(),{page}=enter(f);page.beginExit();page.restoreSite();f.html.scrollTop=0;page.prepare(f.panel,0);assert.equal(page.offset(),2461);page.stage(()=>{});page.commit();assert.equal(page.active,true);page.beginExit();page.finish();assert.deepEqual(f.log.filter(e=>e.type==='scroll').map(e=>e.top),[2461,2461]);assert.equal(f.stage.inert,true);assert.equal(f.reader.scrollTop,713);});
test('fresh reopen captures a new page offset after a completed close and no roots/markers accumulate',()=>{const f=flowFixture(),page=createMobileFlowPage(f.doc),lock=createChatPageLock(f.doc);for(const y of [2461,800,1900]){f.html.scrollTop=y;page.prepare(f.panel,y);lock.lock();page.stage(()=>lock.unlock({restoreScroll:false}));page.commit();page.beginExit();page.finish();assert.equal(f.html.scrollTop,y);}assert.equal(f.body.children.filter(n=>n.className==='mobile-chat-page').length,1);assert.equal(f.body.children.filter(n=>n.tagName==='#COMMENT').length,0);assert.equal(f.world.children.length,1);});
test('one height authority is literal known-good demo CSS; native flow has no fixed/input transform/contain owner',()=>{const css=fs.readFileSync(new URL('../../runtime/chat/chat-mobile-flow.css',import.meta.url),'utf8'),known=fs.readFileSync(new URL('./fixtures/accepted-baseline/send-comparison.css',import.meta.url),'utf8'),owner=fs.readFileSync(new URL('../../runtime/chat/chat-mobile-flow-page.js',import.meta.url),'utf8');for(const token of ['height:100dvh','min-height:0','grid-template-rows:minmax(0,1fr)','overflow:hidden']){assert.ok(css.includes(token));assert.ok(known.includes(token));}assert.match(css,/data-mobile-flow=flow\]\{position:relative!important/);assert.match(css,/data-mobile-flow=flow\] \.canvas-reader\{position:absolute;inset:0/);assert.match(css,/transform:none!important;filter:none!important/);assert.match(css,/backdrop-filter:none;-webkit-backdrop-filter:none;contain:none/);assert.doesNotMatch(owner,/visualViewport|offsetTop|offsetLeft|requestAnimationFrame|setTimeout|\.focus\(|\.blur\(|input\.value|selection/);});

test('native layout can be staged and remeasured while the original panel/input remain disabled outside flow',()=>{const f=flowFixture(),page=createMobileFlowPage(f.doc),lock=createChatPageLock(f.doc);f.input.disabled=true;page.prepare(f.panel,2461);lock.lock();page.stage(()=>lock.unlock({restoreScroll:false}));assert.equal(page.phase,'handoff');assert.equal(page.active,false);assert.equal(f.panel.parentNode,f.body);assert.equal(f.input.disabled,true);assert.equal(f.body.style.position,'');page.commit();assert.equal(page.active,true);assert.equal(f.panel.parentNode,page.frame);assert.equal(f.input.disabled,true);page.beginExit();page.finish();});
