import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {describeChatLayout} from '../../runtime/chat/contextual-chat-layout.js';import {createMobileFlowPage} from '../../runtime/chat/chat-mobile-flow-page.js';import {createChatPageLock} from '../../runtime/chat/chat-page-lock.js';import {flowFixture} from './flow-fixture.mjs';
const host=fs.readFileSync(new URL('../../runtime/chat-host.js',import.meta.url),'utf8'),usableBounds=b=>!!b&&['x','y','w','h'].every(k=>Number.isFinite(b[k]))&&b.w>0&&b.h>0,core={ctx:{requestedMode:'empty'}};
const descriptorLine=host.split('\n').find(l=>l.startsWith(' function mobileDescriptor(')),returnLine=host.split('\n').find(l=>l.startsWith(' function returnBounds('));
function scenario(){const f=flowFixture(),entry=f.site[4];entry.rect={x:276,y:572,w:110,h:44};const source=()=>entry.style.display==='none'?{x:0,y:0,w:0,h:0}:{...entry.rect},actorFrom=source(),page=createMobileFlowPage(f.doc),lock=createChatPageLock(f.doc),descriptor=new Function('core','describeChatLayout','getPresentation','source','actorFrom','usableBounds',descriptorLine+';return mobileDescriptor;')(core,describeChatLayout,()=> 'control',source,actorFrom,usableBounds),returns=new Function('getReturnBounds','getPresentation','flowPage','actorFrom','usableBounds','getReturnBall',returnLine+';return returnBounds;')(source,()=> 'control',page,actorFrom,usableBounds,()=>{throw Error('No real Ball exists in control presentation')});page.prepare(f.panel,2461);lock.lock();return{f,entry,source,actorFrom,page,lock,descriptor,returns};}
test('negative old control branch rejects hidden entry despite a valid retained source',()=>{const s=scenario(),old=descriptorLine.replace('sourceBody:actorFrom,',"sourceBody:getPresentation()==='control'?source():actorFrom||source(),"),broken=new Function('core','describeChatLayout','getPresentation','source','actorFrom','usableBounds',old+';return mobileDescriptor;')(core,describeChatLayout,()=> 'control',s.source,s.actorFrom,usableBounds);assert.doesNotThrow(()=>broken(s.page.measure(),{headHeight:44,composerHeight:70}));s.page.stage(()=>s.lock.unlock({restoreScroll:false}));assert.deepEqual(s.source(),{x:0,y:0,w:0,h:0});assert.throws(()=>broken(s.page.measure(),{headHeight:44,composerHeight:70}),/Non-empty viewport and source body/);s.page.finish();});
test('actual control descriptor survives stage, native flow commit and close using captured positive entry geometry',()=>{const s=scenario(),r=s.page.measure(),metrics={headHeight:44,composerHeight:70};assert.deepEqual(s.descriptor(r,metrics).seed,s.actorFrom);s.page.stage(()=>s.lock.unlock({restoreScroll:false}));assert.deepEqual(s.descriptor(r,metrics).seed,s.actorFrom);assert.deepEqual(s.returns(),s.actorFrom);s.page.commit();assert.deepEqual(s.descriptor(r,metrics).seed,s.actorFrom);const closing=s.page.beginExit();assert.deepEqual(s.descriptor(closing,metrics).seed,s.actorFrom);assert.deepEqual(s.returns(),s.actorFrom);s.page.restoreSite();s.entry.rect={x:276,y:600,w:110,h:44};assert.deepEqual(s.returns(),s.entry.rect);s.page.finish();});
test('a valid fallback appearing after graphics loss can supply return geometry, while hidden absence uses retained source',()=>{const s=scenario();s.page.stage(()=>s.lock.unlock({restoreScroll:false}));assert.ok(usableBounds(s.returns()));s.page.commit();s.page.beginExit();s.page.restoreSite();assert.deepEqual(s.returns(),s.source());s.page.finish();});
test('real Ball return remains dynamic after renderer recovery; unowned desktop preserves its original callback path',()=>{let presentation='actor';const owned={owned:true},actorFrom={x:276,y:572,w:110,h:44},fn=new Function('getReturnBounds','getPresentation','flowPage','actorFrom','usableBounds','getReturnBall',returnLine+';return returnBounds;')(()=>null,()=>presentation,owned,actorFrom,usableBounds,()=>({x:333,y:222,r:24}));assert.deepEqual(fn(),{x:309,y:198,w:48,h:48});presentation='control';assert.deepEqual(fn(),actorFrom);owned.owned=false;const desktop=new Function('getReturnBounds','getPresentation','flowPage','actorFrom','usableBounds','getReturnBall',returnLine+';return returnBounds;')(()=>({x:1,y:2,w:3,h:4}),()=> 'control',owned,actorFrom,usableBounds,()=>{throw Error('No fallback needed')});assert.deepEqual(desktop(),{x:1,y:2,w:3,h:4});});

test('mobile descriptor never remeasures a hidden control and invalid retained source is rejected without a fake center',()=>{const d=new Function('core','describeChatLayout','getPresentation','source','actorFrom','usableBounds',descriptorLine+';return mobileDescriptor;')(core,describeChatLayout,()=> 'control',()=>{throw Error('Hidden entry must never be read')},{x:276,y:572,w:110,h:44},usableBounds);assert.doesNotThrow(()=>d({x:8,y:8,w:386,h:650},{headHeight:44,composerHeight:70}));const invalid=new Function('core','describeChatLayout','getPresentation','source','actorFrom','usableBounds',descriptorLine+';return mobileDescriptor;')(core,describeChatLayout,()=> 'control',()=>{throw Error('No hidden reread')},{x:0,y:0,w:0,h:0},usableBounds);assert.throws(()=>invalid({x:8,y:8,w:386,h:650},{}),/captured entry bounds/);const ret=new Function('getReturnBounds','getPresentation','flowPage','actorFrom','usableBounds','getReturnBall',returnLine+';return returnBounds;')(()=>{throw Error('No hidden fallback measurement')},()=> 'control',{owned:true,siteRemoved:true},{x:276,y:572,w:110,h:44},usableBounds,()=>{throw Error('No replacement Ball')});assert.deepEqual(ret(),{x:276,y:572,w:110,h:44});});
