import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {bootContent,read} from './content-fixture.mjs';
const source=JSON.parse(fs.readFileSync(new URL('../../../../provenance/candidates/alpha5-controls-984814b.json',import.meta.url),'utf8'));
function boot(){return bootContent({width:390,beforeBoot:({d})=>{for(const file of ['style.css','world/scoped.css','host.css','story/story.css','chat/chat-mobile-flow.css']){const style=d.createElement('style');style.textContent=read(file);d.head.append(style);}}});}
const css=(f,s)=>f.w.getComputedStyle(f.$(s)),z=(f,s)=>Number(css(f,s).zIndex);
test('world layer revision changes only two CSS owners; renderer, layout, timing, model and original DOM bytes are exact 984',()=>{for(const {path,sha256}of source.files){if(['runtime/host.css','runtime/chat/chat-mobile-flow.css'].includes(path))continue;assert.equal(crypto.createHash('sha256').update(read(path.slice(8))).digest('hex'),sha256,path);}});
test('normal canvas, grain and UI keep their original paint order below story and header without a root stacking context',()=>{const f=boot();try{assert.equal(css(f,'#ball-world-root').position,'static');assert.equal(css(f,'#ball-world-root').height,'0px');assert.equal(css(f,'#ball-world-root').zIndex,'auto');assert.equal(css(f,'#world-stage').position,'fixed');assert.equal(css(f,'#world-home').position,'fixed');assert.equal(z(f,'#world-stage'),20);assert.equal(z(f,'.grain'),21);assert.equal(z(f,'#world-home'),21);assert(f.$('.grain').compareDocumentPosition(f.$('#world-home'))&f.w.Node.DOCUMENT_POSITION_FOLLOWING,'Equal-tier UI follows grain in the immutable markup');assert(z(f,'#world-home')<z(f,'#story-content-layer'));assert(z(f,'.grain')<z(f,'.topbar'));assert.equal(css(f,'#world-home').pointerEvents,'none');assert.equal(css(f,'#world-ball-hit').pointerEvents,'auto');assert.equal(f.d.querySelectorAll('.grain').length,1);}finally{f.close();}});
test('reading promotes only the existing actor/UI above header and below host popovers',()=>{const f=boot();try{const nodes=['#ball-world-root','#world-stage','.grain','#world-home','#world-ball-hit'].map(s=>f.$(s)),parents=nodes.map(n=>n.parentNode);for(let i=0;i<3;i++){f.w.contentStudy.open('work-context',{push:false});f.settle();assert.equal(z(f,'#world-stage'),31);assert.equal(z(f,'#world-home'),32);assert.equal(z(f,'.grain'),21);assert(z(f,'.topbar')<z(f,'#world-stage'));assert(z(f,'#world-home')<z(f,'#host-overlays'));f.w.contentStudy.close('test',{history:false});f.settle();assert.equal(z(f,'#world-stage'),20);}nodes.forEach((n,i)=>assert.equal(n.parentNode,parents[i]));assert.equal(f.d.querySelectorAll('.grain').length,1);}finally{f.close();}});
test('chat keeps the former canvas, grain, UI order and precedence over a suspended reader',()=>{const f=boot();try{f.d.body.dataset.readingAssistant='true';f.d.body.dataset.chatOpen='true';assert.equal(z(f,'#world-stage'),60);assert.equal(z(f,'.grain'),61);for(const selector of ['#world-home','#world-speech','#world-entry-note','#world-fallback'])assert.equal(z(f,selector),62);assert.equal(css(f,'#ball-world-root').zIndex,'auto');f.d.body.dataset.chatOpen='false';assert.equal(z(f,'#world-stage'),31);assert.equal(z(f,'.grain'),21);}finally{f.close();}});
test('mobile viewport clipping belongs to full fixed paint/UI layers rather than the zero-height owner',()=>{const f=boot();try{f.d.body.dataset.mobileChatPage='true';assert.equal(css(f,'#ball-world-root').overflow,'visible');for(const selector of ['#world-stage','#world-home']){assert.equal(css(f,selector).overflow,'clip');assert.equal(css(f,selector).position,'fixed');assert.notEqual(css(f,selector).transform,'translateZ(0)');}assert.doesNotMatch(read('chat/chat-mobile-flow.css'),/data-mobile-chat-page=true\] #ball-world-root\{overflow:clip\}/);}finally{f.close();}});
test('unavailable world hides all paint despite inline-visible homepage and recovers the same semantic owner',()=>{const f=boot();try{const root=f.$('#ball-world-root'),home=f.$('#world-homepage');home.style.visibility='visible';f.d.body.dataset.worldAvailability='fallback';assert.equal(css(f,'#ball-world-root').display,'none');f.d.body.dataset.worldAvailability='ready';assert.notEqual(css(f,'#ball-world-root').display,'none');assert.equal(f.$('#world-homepage'),home);assert.equal(f.$('#ball-world-root'),root);}finally{f.close();}});
