import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {bootContent,read} from './content-fixture.mjs';import {bootHost} from './host-fixture.mjs';import {readingClearance,intersection} from './reading-clearance.mjs';
const before=name=>fs.readFileSync(new URL('./fixtures/reading-before/'+name,import.meta.url),'utf8');
const shelfFor=f=>f.w.personalOSContent.getReadingAssistant?.();
function boot({width=390,height=844,safe=0,old=false}={}){return bootContent({width,appSource:old?before('app.js'):read('app.js'),beforeBoot:({w,d})=>{Object.defineProperty(w,'innerHeight',{value:height,configurable:true});d.documentElement.style.setProperty('--safe-bottom',safe+'px');}});}
const zero=n=>Math.abs(n)<1e-7;
test('reading negative fixtures are independently pinned exact initial-alpha.5 bytes',()=>{const expected=JSON.parse(before('sha256.json'));for(const [file,hash]of Object.entries(expected))assert.equal(crypto.createHash('sha256').update(before(file)).digest('hex'),hash);});
for(const size of [{width:320,height:568},{width:390,height:844},{width:430,height:932,safe:34},{width:390,height:300},{width:390,height:284}])test(`mobile ${size.width}×${size.height} reserves disjoint reader and explicit actor shelf from the initial target`,()=>{
 const f=boot(size),old=boot({...size,old:true});try{for(const q of [f,old])q.w.contentStudy.open('work-context',{push:false});const s=f.w.contentStudy.snapshot(),o=old.w.contentStudy.snapshot(),shelf=shelfFor(f);assert(shelf);assert.equal(f.$('#reader-assistant-rail').hidden,false);assert.equal(s.target.h+shelf.h+12,o.target.h);for(const k of ['x','y','w','ix','iy','bx','by','scale'])assert.equal(s.target[k],o.target[k],k);assert.equal(f.$('.detail-body').style.fontSize,old.$('.detail-body').style.fontSize);assert(s.target.y+s.target.h<=shelf.y-12+.01);assert(shelf.actor.x>=shelf.x&&shelf.actor.y>=shelf.y);assert(shelf.actor.y+shelf.actor.h<=shelf.y+shelf.h);assert.equal(s.phase,'intermediate');f.settle();assert.deepEqual(shelfFor(f),shelf);assert.equal(f.$('#reader').classList.contains('reading'),true);}finally{f.close();old.close();}
});
test('desktop frame, native body width and target geometry remain equal to initial alpha.5',()=>{const f=boot({width:1280}),old=boot({width:1280,old:true});try{for(const q of [f,old])q.w.contentStudy.open('work-context',{push:false});assert.deepEqual(JSON.parse(JSON.stringify(f.w.contentStudy.snapshot().target)),JSON.parse(JSON.stringify(old.w.contentStudy.snapshot().target)));assert.equal(shelfFor(f),null);assert.equal(f.$('#reader-assistant-rail').hidden,true);}finally{f.close();old.close();}});
test('same native article/reader restore their feed position/focus on return and interrupted reopens retain the shelf',()=>{const f=boot();try{const article=f.$('[data-content-id="work-context"]'),reader=f.$('#reader'),button=article.querySelector('.open-card');f.d.scrollingElement.scrollTop=780;f.w.contentStudy.open('work-context',{push:false});f.settle();reader.scrollTop=613;f.w.contentStudy.close('test',{history:false});f.w.contentStudy.advance(.05);assert.equal(f.$('#reader-assistant-rail').hidden,false);f.w.contentStudy.open('work-context',{push:false});f.settle();assert.equal(f.$('#canvas').firstElementChild,article);assert.equal(f.$('#reader'),reader);f.w.contentStudy.close('test',{history:false});f.settle();assert.equal(article.parentElement.dataset.id,'work-context');assert.equal(f.d.scrollingElement.scrollTop,780);assert.equal(f.d.activeElement,button);assert.equal(f.$('#reader-assistant-rail').hidden,true);assert.equal(f.d.body.dataset.readingAssistant,'false');assert.equal(f.d.querySelectorAll('article.card').length,18);}finally{f.close();}});
test('actual host placement consumes cached shelf actor bounds without DOM measurements per world frame',async()=>{const f=await bootHost({width:390});try{f.w.contentStudy.open('work-context',{push:false});f.settle();const expected=shelfFor(f).actor;const get=f.w.HTMLElement.prototype.getBoundingClientRect;f.w.HTMLElement.prototype.getBoundingClientRect=()=>{throw Error('New per-frame DOM measurement');};try{for(let i=0;i<30;i++){const p=f.placement({x:160,y:250,r:70});assert.equal(p.mode,'reading');assert.deepEqual(p.bounds,expected);}}finally{f.w.HTMLElement.prototype.getBoundingClientRect=get;}f.w.contentStudy.close('test',{history:false});f.settle();assert.equal(f.placement({x:160,y:250,r:70}).mode,'hero');}finally{f.close();}});
test('synthetic native-scroll oracle detects old overlap and preserves clearance at start/middle/deep/end',()=>{
 const old=boot({old:true}),next=boot();try{for(const f of [old,next]){f.w.contentStudy.open('work-context',{push:false});f.settle();}const oldReader=old.w.contentStudy.snapshot().target,newReader=next.w.contentStudy.snapshot().target,shelf=shelfFor(next),oldActor={x:294,y:716,w:48,h:48},caption={x:shelf.actor.x+24-60,y:shelf.actor.y+53.2,w:120,h:16};
  // A conservative line-box train is synthetic; actual Range rectangles are a separate browser gate.
  for(const offset of [0,337,912,1800]){const textRects=Array.from({length:100},(_,i)=>({x:36,y:140+i*31-offset,w:300,h:27}));const result=readingClearance({reader:newReader,textRects,obstacles:{actor:shelf.actor,caption},shelf});assert(result.visibleLines>0);assert.equal(result.clear,true);assert.equal(result.readerEndsAboveShelf,true);assert.equal(result.shelfContainsObstacles,true);const negative=readingClearance({reader:oldReader,textRects,obstacles:{actor:oldActor,caption:{x:260,y:810,w:110,h:16}},shelf:null});assert.equal(negative.clear,false,`old layout should collide at ${offset}`);}
 }finally{old.close();next.close();}
});
test('oracle ignores ink outside the native clip and catches partially visible line collisions',()=>{assert.equal(intersection({x:0,y:100,w:10,h:10},{x:0,y:0,w:20,h:90}),null);const result=readingClearance({reader:{x:0,y:0,w:100,h:100},textRects:[{x:0,y:90,w:100,h:20}],obstacles:{actor:{x:70,y:95,w:20,h:20}},shelf:null});assert.equal(result.clear,false);assert.equal(result.collisions[0].overlap.h,5);});
test('reading reservation is an intent-time outer target, never a detail-time height toggle or per-frame layout write',()=>{const source=read('app.js'),paint=source.slice(source.indexOf('function paint()'),source.indexOf('function open('));assert.doesNotMatch(paint,/configureReadingAssistant|readingRail|reading-assistant/);const finished=source.slice(source.indexOf('function finishOpen()'),source.indexOf('function compensateReading'));assert.doesNotMatch(finished,/configureReadingAssistant|readingRail|height/);assert.match(source,/h:available-\(assistant\?assistant.h\+12:0\)/);assert.doesNotMatch(read('host.css'),/\.reader\.reading\s*\{[^}]*padding|\.reader\.reading\s*\{[^}]*height/);});

test('the 80 px minimum shelf contains the full 50.4 px original hit target and unchanged caption',()=>{const f=boot({width:390,height:284});try{f.w.contentStudy.open('work-context',{push:false});const shelf=shelfFor(f),a=shelf.actor;assert.equal(shelf.h,80);assert.equal(f.w.contentStudy.snapshot().target.h,104);const hit={x:a.x-1.2,y:a.y-1.2,w:50.4,h:50.4},caption={x:a.x+24-60,y:a.y+53.2,w:120,h:16};assert(readingClearance({reader:f.w.contentStudy.snapshot().target,textRects:[],obstacles:{actor:a,button:hit,caption},shelf}).shelfContainsObstacles);assert.match(read('host.css'),/top:clamp\(calc\(100% \+ 4px\),calc\(200% - 46.4px\),calc\(125% \+ 32px\)\)/);}finally{f.close();}});
test('reading modal routes Tab through the available original assistant and suspends ownership during chat',()=>{
 const f=boot();try{f.$('#world-homepage').inert=false;f.d.body.dataset.worldAvailability='ready';f.w.contentStudy.open('work-context',{push:false});f.settle();const shell=f.$('#shell'),actor=f.$('#world-ball-hit'),close=f.$('#close'),body=f.$('#canvas .detail-body'),last=[...body.querySelectorAll('button,a')].at(-1)||close,reader=f.$('#reader');reader.scrollTop=413;assert.equal(shell.getAttribute('aria-owns'),'world-ball-hit');
 const tab=shift=>f.d.dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'Tab',shiftKey:shift,bubbles:true,cancelable:true}));last.focus();tab(false);assert.equal(f.d.activeElement,actor);tab(true);assert.equal(f.d.activeElement,last);last.focus();tab(false);tab(false);assert.equal(f.d.activeElement,close);assert.equal(reader.scrollTop,413);
 f.w.dispatchEvent(new f.w.CustomEvent('personalos:chat-state',{detail:{open:true,phase:'opening'}}));assert.equal(shell.hasAttribute('aria-owns'),false);f.w.dispatchEvent(new f.w.CustomEvent('personalos:chat-state',{detail:{open:false,phase:'closing'}}));assert.equal(shell.hasAttribute('aria-owns'),false);f.w.dispatchEvent(new f.w.CustomEvent('personalos:chat-state',{detail:{open:false,phase:'closed'}}));assert.equal(shell.getAttribute('aria-owns'),'world-ball-hit');
 const fallback=f.d.createElement('aside');fallback.id='host-chat-fallback';fallback.innerHTML='<button id="host-open-chat">打开聊天</button>';f.d.body.append(fallback);f.d.body.dataset.worldAvailability='fallback';f.w.dispatchEvent(new f.w.CustomEvent('personalos:host-state'));assert.equal(shell.getAttribute('aria-owns'),'host-open-chat');last.focus();tab(false);assert.equal(f.d.activeElement,f.$('#host-open-chat'));f.d.body.dataset.worldAvailability='ready';f.w.dispatchEvent(new f.w.CustomEvent('personalos:host-state'));assert.equal(shell.getAttribute('aria-owns'),'world-ball-hit');
 f.w.contentStudy.close('test',{history:false});f.settle();assert.equal(shell.hasAttribute('aria-owns'),false);assert.equal(f.$('#reader'),reader);assert.deepEqual(f.errors,[]);
 }finally{f.close();}
});

test('explicit assistant Tab routing preserves native scrolling to offscreen article controls',()=>{
 const f=boot();try{f.$('#world-homepage').inert=false;f.d.body.dataset.worldAvailability='ready';f.w.contentStudy.open('work-context',{push:false});f.settle();const actor=f.$('#world-ball-hit'),body=f.$('#canvas .detail-body'),last=[...body.querySelectorAll('button,a')].at(-1);assert(last);const calls=[];const native=last.focus.bind(last);last.focus=(...args)=>{calls.push(args);return native(...args);};actor.focus();f.d.dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}));assert.equal(f.d.activeElement,last);assert.deepEqual(calls,[[]],'Body target must use ordinary focus to reveal its native scroll position');const fixed=actor.focus.bind(actor),fixedCalls=[];actor.focus=(...args)=>{fixedCalls.push(args);return fixed(...args);};f.d.dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}));assert.equal(f.d.activeElement,actor);assert.equal(fixedCalls[0][0].preventScroll,true);
 }finally{f.close();}
});

test('reading focus ring remains within the minimum shelf and cannot strike the compact caption',()=>{const f=boot({width:390,height:284});try{f.w.contentStudy.open('work-context',{push:false});const shelf=shelfFor(f),a=shelf.actor,hit={x:a.x-1.2,y:a.y-1.2,w:50.4,h:50.4},caption={x:a.x+24-60,y:a.y+53.2,w:120,h:16};const expand=(b,n)=>({x:b.x-n,y:b.y-n,w:b.w+n*2,h:b.h+n*2});const good=readingClearance({reader:f.w.contentStudy.snapshot().target,textRects:[],obstacles:{actor:a,button:hit,caption,focusRing:expand(hit,4)},shelf});assert(good.shelfContainsObstacles);assert(good.captionClearOfFocusRing);const old=readingClearance({reader:f.w.contentStudy.snapshot().target,textRects:[],obstacles:{caption,focusRing:expand(hit,14)},shelf});assert.equal(old.captionClearOfFocusRing,false);assert.match(read('host.css'),/#world-ball-hit:focus-visible\{outline-offset:2px\}/);}finally{f.close();}});

test('oracle ignores IEEE-754 touching-edge noise but rejects actual rendered-size overlap',()=>{assert.equal(intersection({x:0,y:160.8,w:50,h:58.4},{x:0,y:219.2,w:50,h:16}),null);assert(intersection({x:0,y:160.8,w:50,h:58.4},{x:0,y:219.2-1/64,w:50,h:16}));});


test('reader controls reserve their final native area at selection with only the existing progress driving the source-plane bridge',()=>{const f=boot();try{f.w.contentStudy.open('work-context',{push:false});const reader=f.$('#reader'),canvas=f.$('#canvas'),header=f.$('#reader-controls'),shell=f.$('#shell');assert.equal(header.hidden,false);assert.equal(shell.style.getPropertyValue('--reader-controls-height'),'64px');assert.equal(shell.dataset.readingControls,'true');assert.equal(canvas.style.transform,'translate3d(0,-64px,0)');for(const p of [.25,.5,1,.5,0]){f.w.contentStudy.seek(p);assert.equal(canvas.style.transform,`translate3d(0,${-64*(1-p)}px,0)`);assert.equal(header.style.opacity,String(p));}f.w.contentStudy.open('work-context',{push:false});f.settle();assert.equal(reader.classList.contains('reading'),true);assert.equal(canvas.style.transform,'translate3d(0,0px,0)');assert.equal(f.$('#reader'),reader);f.w.contentStudy.close('test',{history:false});assert.equal(reader.classList.contains('reading'),false,'Zero-scroll return releases the native clip before bridging back to the card');f.w.contentStudy.advance(.05);assert.equal(header.hidden,false);f.settle();assert.equal(header.hidden,true);assert.equal(canvas.style.transform,'');}finally{f.close();}});

test('return removes the native reading clip in the same turn for both zero and deep scroll',()=>{for(const offset of [0,613]){const f=boot();try{f.w.contentStudy.open('work-context',{push:false});f.settle();f.$('#reader').scrollTop=offset;const before=f.w.contentStudy.snapshot();f.w.contentStudy.close('test',{history:false});const after=f.w.contentStudy.snapshot();assert.equal(f.$('#reader').classList.contains('reading'),false);assert.equal(f.$('#reader').scrollTop,0);assert.equal(after.pose.iy,before.pose.iy-offset);assert.equal(after.pose.by,before.pose.by-offset);}finally{f.close();}}});


test('the native clip oracle rejects fixed Close over visible body ink and approves a disjoint control region',()=>{const ink=[{x:36,y:111,w:310,h:27},{x:36,y:172,w:310,h:27}],close={x:322,y:92,w:40,h:40};const old=readingClearance({reader:{x:13,y:77,w:364,h:654},textRects:ink,obstacles:{close},shelf:null});assert.equal(old.clear,false);assert.equal(old.readerStartsBelowClose,false);assert(old.collisions.some(c=>c.name==='close'));const next=readingClearance({reader:{x:13,y:141,w:364,h:590},textRects:ink,obstacles:{close},shelf:null});assert.equal(next.clear,true);assert.equal(next.readerStartsBelowClose,true);assert.equal(next.visibleLines,1);});


test('caption placement has no phase discontinuity at return and preserves the large hero rule',()=>{const css=read('host.css'),caption=[...css.matchAll(/#ball-world-root \.ball-hint\{[^}]+\}/g)].at(-1)[0],reading=css.match(/body\[data-reading-assistant=true\] #ball-world-root \.ball-hint\{[^}]+\}/)[0];assert.match(caption,/top:clamp/);assert.doesNotMatch(reading,/(?:^|;)top:/);const top=h=>Math.max(h+4,Math.min(2*h-46.4,1.25*h+32));assert(Math.abs(top(50.4)-54.4)<1e-10);assert.equal(top(147),1.25*147+32);for(const h of [50.4,78.4/.75])assert(Math.abs(top(h-1e-5)-top(h+1e-5))<5e-5);const actorY=778,hit=50.4;assert(actorY-hit/2+top(hit)+16<844,'Same caption remains on screen during the first preview frame before world spring returns');});
