/* Additive paint contract. This module has no renderer, scroll engine or animation clock. */
const phases=new Set(['entry','handoff','content','reading','return']);
const colorTokens={field:'--bg',ink:'--ink',muted:'--muted',edge:'--stroke',work:'--surface-work',thoughts:'--surface-thoughts',labs:'--surface-labs',workTone:'--tone-work',thoughtsTone:'--tone-thoughts',labsTone:'--tone-labs'};
let revision=0;const state={sceneId:'still-life',phase:'content',progress:1,revision:0,actorBounds:null,material:Object.fromEntries(Object.entries(colorTokens).map(([key,variable])=>[key,getComputedStyle(document.documentElement).getPropertyValue(variable).trim()]))};
const box=element=>{const b=element.getBoundingClientRect();return{x:b.x,y:b.y,w:b.width,h:b.height}};
function metrics(){const content=window.personalOSContent?.getState();return{scrollOffset:document.querySelector('#page-scroll').scrollTop,readerOffset:document.querySelector('#reader').scrollTop,contentId:content?.contentId||null,category:content?.category||'all',phase:content?.phase||'preview',displayBounds:content?.shell||null,innerLayout:content?.native||null,rootTransform:getComputedStyle(document.querySelector('.app')).transform}}
function getAvoidBounds(){const values=[{role:'header',...box(document.querySelector('.topbar'))},{role:'filters',...box(document.querySelector('.filters'))}];const content=window.personalOSContent?.getState();if(content?.shell)values.push({role:'content',...content.shell});return values}
function apply(input={}){if(input.sceneId&&input.sceneId!=='still-life')return{accepted:false,reason:'scene-owner-mismatch'};if(input.phase&&!phases.has(input.phase))return{accepted:false,reason:'unsupported-phase'};const before=metrics();if(input.phase)state.phase=input.phase;if(Number.isFinite(input.progress))state.progress=Math.min(1,Math.max(0,input.progress));if(input.actorBounds)state.actorBounds={...input.actorBounds};const changed=[];for(const[key,value]of Object.entries(input.material||{})){if(colorTokens[key]&&typeof value==='string'&&CSS.supports('color',value)){document.documentElement.style.setProperty(colorTokens[key],value);state.material[key]=value;changed.push(key)}}state.revision=++revision;document.body.dataset.scenePhase=state.phase;const detail={version:1,...state,changedPaintTokens:changed,before,after:metrics(),avoidBounds:getAvoidBounds(),coordinateSpace:'viewport-css-px',responsibility:'paint-only'};window.dispatchEvent(new CustomEvent('personalos:scene-accepted',{detail}));return{accepted:true,revision,metrics:detail.after}}
// Continuous ambient color uses a paint-only fast path, with no geometry reads.
function paint(material={}){const changed=[];for(const[key,value]of Object.entries(material)){const variable=colorTokens[key];if(variable&&typeof value==='string'&&CSS.supports('color',value)&&state.material[key]!==value){document.documentElement.style.setProperty(variable,value);state.material[key]=value;changed.push(key);}}if(changed.length)state.revision=++revision;return{accepted:true,changedPaintTokens:changed,revision};}
window.personalOSSceneBridge={version:2,apply,paint,getState:()=>({...state,metrics:metrics(),avoidBounds:getAvoidBounds()}),getAvoidBounds,subscribe(callback){const handler=e=>callback(e.detail);window.addEventListener('personalos:scene-accepted',handler);return()=>window.removeEventListener('personalos:scene-accepted',handler)}};
document.body.dataset.scenePhase='content';
