"""One finite all-object lower daylight-bounce card; camera visibility cheat explicit."""
import bpy,numpy as np,json,hashlib,math
from pathlib import Path
D=Path(__file__).parent;SRC=D/'PersonalOS-visible-straight-shaft-geometry-candidate.blend';SHA='c0d88ae98880486fca4fbc4f1703c01413d93af841ce23014800e6e642267c94';assert hashlib.sha256(SRC.read_bytes()).hexdigest()==SHA
bpy.ops.wm.open_mainfile(filepath=str(SRC));s=bpy.context.scene;s.frame_set(49);bpy.context.view_layer.update()
wn=next(n for n in s.world.node_tree.nodes if n.type=='TEX_IMAGE');arr=np.empty(len(wn.image.pixels),np.float32);wn.image.pixels.foreach_get(arr);worldhash=hashlib.sha256(arr.tobytes()).hexdigest()
name='Studio / finite lower daylight bounce reflection card';mesh=bpy.data.meshes.new(name);mesh.from_pydata([(1.3,2.4,.2),(3.8,2.4,.2),(3.8,6.7,.2),(1.3,6.7,.2)],[],[(0,1,2,3)]);mesh.update();uv=mesh.uv_layers.new(name='PhysicalCardUV');uv.data.foreach_set('uv',np.array([(0,0),(1,0),(1,1),(0,1)],np.float32).ravel());o=bpy.data.objects.new(name,mesh);s.collection.objects.link(o);o.visible_camera=False
for attr in ['visible_diffuse','visible_glossy','visible_transmission','visible_volume_scatter','visible_shadow']:
 if hasattr(o,attr):setattr(o,attr,True)
mat=bpy.data.materials.new('Studio card / shared neutral-cool raised-cosine emission');mat.use_nodes=True;nt=mat.node_tree;nt.nodes.clear();tex=nt.nodes.new('ShaderNodeTexCoord');sep=nt.nodes.new('ShaderNodeSeparateXYZ');nt.links.new(tex.outputs['UV'],sep.inputs[0]);factors=[]
for c in ['X','Y']:
 scale=nt.nodes.new('ShaderNodeMath');scale.operation='MULTIPLY';scale.inputs[1].default_value=math.pi;nt.links.new(sep.outputs[c],scale.inputs[0]);sin=nt.nodes.new('ShaderNodeMath');sin.operation='SINE';nt.links.new(scale.outputs[0],sin.inputs[0]);square=nt.nodes.new('ShaderNodeMath');square.operation='MULTIPLY';nt.links.new(sin.outputs[0],square.inputs[0]);nt.links.new(sin.outputs[0],square.inputs[1]);factors.append(square.outputs[0])
mul=nt.nodes.new('ShaderNodeMath');mul.operation='MULTIPLY';nt.links.new(factors[0],mul.inputs[0]);nt.links.new(factors[1],mul.inputs[1]);gain=nt.nodes.new('ShaderNodeMath');gain.operation='MULTIPLY';gain.inputs[1].default_value=4.;nt.links.new(mul.outputs[0],gain.inputs[0]);emit=nt.nodes.new('ShaderNodeEmission');Y=np.array([.2126,.7152,.0722]);rgb=np.array([.95,1.,1.08]);rgb/=rgb@Y;emit.inputs['Color'].default_value=(*rgb,1);nt.links.new(gain.outputs[0],emit.inputs['Strength']);geo=nt.nodes.new('ShaderNodeNewGeometry');trans=nt.nodes.new('ShaderNodeBsdfTransparent');mix=nt.nodes.new('ShaderNodeMixShader');nt.links.new(geo.outputs['Backfacing'],mix.inputs[0]);nt.links.new(emit.outputs[0],mix.inputs[1]);nt.links.new(trans.outputs[0],mix.inputs[2]);out=nt.nodes.new('ShaderNodeOutputMaterial');nt.links.new(mix.outputs[0],out.inputs['Surface']);mesh.materials.append(mat)
o['purpose']='Art-directed lower wet-ground/daylight bounce approximation; fixed in world space; not a physically inferred source';o['visibility_cheat']='Camera-invisible finite emitter; shared for all other ray types and all objects, not glossy-only';o['peak_scene_linear_luminance']=4.;o['emission_profile']='sin(pi*u)^2 * sin(pi*v)^2, broad two-dimensional raised cosine; zero at all four edges';o['not_target_projection']=True
verify=np.empty(len(wn.image.pixels),np.float32);wn.image.pixels.foreach_get(verify);assert np.array_equal(arr,verify);report={'source_sha256':SHA,'card_world_bounds':{'x':[1.3,3.8],'y':[2.4,6.7],'z':.20},'card_size_metres':[2.5*15/88,4.3*15/88],'source_type':'One-sided +Z finite mesh emitter','emission_peak_Y':4.,'RGB_luminance_normalized':rgb.tolist(),'emission_profile':'sin(pi*u)^2 * sin(pi*v)^2; broad raised-cosine falloff','camera_invisible':True,'shared_other_ray_types':True,'all_object_visibility':True,'glossy_only':False,'world_pixel_sha256_unchanged':worldhash,'geometry_variants':False,'physical_status':'Explicit film-lighting approximation of wet-ground daylight bounce; camera-invisible emitter is not fully physical','analytic_Ball_estimate_caveat':'Previous uniform-interior calculation is an upper bound for this lower-energy cosine profile; secondary bounce and edge glints need actual crop review'}
OUT=D/'PersonalOS-visible-shaft-and-reflection-card-candidate.blend';bpy.ops.wm.save_as_mainfile(filepath=str(OUT),compress=True);report['candidate_sha256']=hashlib.sha256(OUT.read_bytes()).hexdigest();(D/'SELECTED-SHAFT-AND-CARD-BUILD.json').write_text(json.dumps(report,indent=2));print(json.dumps(report),flush=True)
