import bpy,numpy as np,json,hashlib
from pathlib import Path
from mathutils import Vector
from mathutils.bvhtree import BVHTree
D=Path(__file__).parent;P=D/'PersonalOS-continuous-roof-relief-crop-candidate.blend';bpy.ops.wm.open_mainfile(filepath=str(P));s=bpy.context.scene;s.frame_set(49);bpy.context.view_layer.update();o=s.objects['Dry clay / eight tensioned gores'];m=o.data;N=len(m.vertices)//2;v=np.empty((len(m.vertices),3));m.vertices.foreach_get('co',v.ravel());M=np.array(o.matrix_world);v=v@M[:3,:3].T+M[:3,3];m.calc_loop_triangles();alltri=np.empty((len(m.loop_triangles),3),np.int32);m.loop_triangles.foreach_get('vertices',alltri.ravel());outer=alltri[np.max(alltri,axis=1)<N];inner=alltri[np.min(alltri,axis=1)>=N]-N;edgeids=np.empty(len(m.loops),np.int32);m.loops.foreach_get('edge_index',edgeids);counts=np.bincount(edgeids,minlength=len(m.edges));dist=np.linalg.norm(v[:N]-v[N:],axis=1)*15/88*1000
# Verify BVH overlap performs triangle tests, not only bounding-box overlap.
a=np.array([[0,0,0],[1,0,1],[0,1,1]],float);b=a+np.array([-.001,-.001,.001]);assert not BVHTree.FromPolygons(a,[(0,1,2)],all_triangles=True).overlap(BVHTree.FromPolygons(b,[(0,1,2)],all_triangles=True))
T=BVHTree.FromPolygons(v[:N],outer,all_triangles=True);I=BVHTree.FromPolygons(v[N:],inner,all_triangles=True);cross=T.overlap(I);bc=s.objects['BallBody / one original spherical actor'].matrix_world.translation;near=T.find_nearest(bc);clearance=(near[3]-.88)*15/88*1000
water=[]
for name in ['Readable wetness / microbeads','Readable wetness / small_beads','Readable wetness / coalesced_beads','Wet PVC / native900 restrained resolved wetness']:
 w=s.objects[name];pv=np.empty((len(w.data.vertices),3));w.data.vertices.foreach_get('co',pv.ravel());mw=np.array(w.matrix_world);pv=pv@mw[:3,:3].T+mw[:3,3];hits=[T.find_nearest(Vector(p)) for p in pv];signed=np.array([(Vector(p)-h[0]).dot(h[1]) for p,h in zip(pv,hits)])*15/88*1000;dd=np.array([h[3] for h in hits])*15/88*1000;near=signed[dd<.3];w.data.calc_loop_triangles();wt=np.array([t.vertices for t in w.data.loop_triangles]);overlap=len(T.overlap(BVHTree.FromPolygons(pv,wt,all_triangles=True)));water.append({'name':name,'water_roof_triangle_intersections':overlap,'sampled_vertices':len(pv),'near_surface_vertices':len(near),'near_surface_signed_clearance_mm_percentiles':np.percentile(near,[0,1,5,50,100]).tolist() if len(near) else None,'near_surface_negative_vertices':int(np.sum(near<-.001))})
r={'master_sha256':hashlib.sha256(P.read_bytes()).hexdigest(),'closed_manifold_all_edges_two_faces':bool(np.all(counts==2)),'edge_incidence_minmax':[int(counts.min()),int(counts.max())],'paired_shell_thickness_mm_minmax':[float(dist.min()),float(dist.max())],'outer_inner_triangle_intersection_pairs':len(cross),'roof_Ball_clearance_mm':clearance,'water_reseated_signed_probes':water,'scope':'Paired shell intersection and edge manifold audit; source structural geometry unchanged; numerical nearest-surface water probes, not a fluid simulation'};(D/'CONTINUOUS-SCENE-GEOMETRY-AUDIT.json').write_text(json.dumps(r,indent=2));print(json.dumps(r),flush=True);assert np.all(counts==2) and not cross and clearance>0 and all(q['water_roof_triangle_intersections']==0 for q in water)
