import { records, graphic, detail } from './demo-content';
import { categories, routeURL, type RouteState } from '../navigation/route-state';
export const escapeHTML = (value: string): string => value.replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export function renderContent(state: RouteState): string {
  const article = (record: typeof records[number]) => `<article class="card" data-content-id="${record.id}" data-category="${record.category}" aria-labelledby="title-${record.id}"><div class="identity"><div class="card-meta"><span class="category">${record.category.toUpperCase()}</span><span>PLACEHOLDER</span><span class="card-index">${record.index}</span></div><h2 id="title-${record.id}">${escapeHTML(record.title)}</h2><p class="summary">${escapeHTML(record.summary)}</p><figure class="card-visual" style="margin-left:0;margin-right:0">${graphic(record.kind)}</figure><div class="card-foot"><span>${escapeHTML(record.meta)}</span><span class="open-label">Open +</span></div></div><div class="detail-body">${detail(record)}</div><a class="open-card" href="${escapeHTML(routeURL({...state, item: record.id, category: record.category}, 'http://localhost/').search)}" aria-label="打开 ${escapeHTML(record.title)}">打开文章</a></article>`;
  const selected = records.find(record => record.id === state.item);
  const filters = categories.map(category => `<a data-filter="${category}" aria-pressed="${state.category === category}" href="${escapeHTML(routeURL({category,item:null,chat:false}, 'http://localhost/').search || '/')}">${category === 'all' ? 'All' : category[0].toUpperCase()+category.slice(1)} <span>${category === 'all' ? '18' : '06'}</span></a>`).join('');
  return `<div class="app" data-entry="home"><div class="page-scroll" id="page-scroll"><main id="content-root"><div class="intro"><div class="eyebrow">A PLACE FOR THINGS IN PROGRESS</div><h1>Work<span>,</span><br>Thoughts <span>&</span> Labs<span>.</span></h1><div class="intro-note"><p>做的事，想的事，<br>正在试的事。</p><p class="example-note">以下为公开知识与演示内容，<br>不代表个人项目或经历。</p></div></div><div id="category-anchor" aria-hidden="true"></div><nav class="filters" aria-label="内容栏目"><div class="filter-indicator" aria-hidden="true"></div>${filters}</nav><section class="feed" id="feed" tabindex="-1" aria-label="混合内容瀑布流">${records.map(record => `<div class="slot" data-id="${record.id}" style="--height:${record.height}px">${selected?.id === record.id ? '' : article(record)}</div>`).join('')}</section><footer><span>18 fragments, three equal spaces.</span><span>Next SSR migration proof · alpha.3 content</span></footer></main></div></div><div class="transition-stage" id="stage" ${selected ? 'data-ssr-reader="true"' : 'hidden'}><div class="backdrop" aria-hidden="true"></div><div class="travel-shell" id="shell" role="region" tabindex="-1" ${selected ? `aria-labelledby="title-${selected.id}"` : ''}><div class="reader" id="reader"><div class="content-canvas" id="canvas">${selected ? article(selected) : ''}</div></div><a class="close" id="close" href="${escapeHTML(routeURL({...state,item:null}, 'http://localhost/').search || '/')}" aria-label="关闭详情">×</a></div></div><div id="story-content-layer" hidden inert aria-hidden="true"></div><div class="sr-only" id="announcer" aria-live="polite"></div><p data-chat-scope ${state.chat ? '' : 'hidden'}>此迁移候选尚未挂载聊天；原版聊天保持不变。</p>`;
}
